samples : "samples.tsv"
sample_gibcus: "sample_gibcus.tsv"
units : 'units.tsv'
reference: 'data/input/fa/mm10.fa'
low_res : 400000
high_res : 10000

region :  "chr1"

contact_maps:
  max_res   : 10000
  comp_res  : 100000